title: FutureCrop Lab
email: futurecrop@youruniversity.edu
description: >
  The FutureCrop Lab pioneers interdisciplinary research at the nexus of crop biology, AI, and synthetic systems to reimagine agriculture for a sustainable future.
baseurl: ""
url: "https://your_username.github.io/futurecrop-lab"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
